apiVersion: v1
kind: Service
metadata:
  name: homeassistant-shared
  namespace: shared
spec:
  type: ExternalName
  externalName: homeassistant.homeassistant.svc.cluster.local
  ports:
  - port: 8123
