apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      hostNetwork: true
      containers:
      - name: homeassistant
        image: homeassistant/home-assistant:stable
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8123
          name: web
        volumeMounts:
        - name: homeassistant-config
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        env:
        - name: TZ
          value: "America/Denver"
        - name: DB_URL
          value: "postgresql://finances:password@postgres-shared.shared.svc.cluster.local:5432/homeassistant"
        livenessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
      volumes:
      - name: homeassistant-config
        persistentVolumeClaim:
          claimName: homeassistant-pvc
      - name: localtime
        hostPath:
          path: /etc/localtime
            
