apiVersion: v1
kind: ConfigMap
metadata:
  name: finances-app-config
  namespace: finances-app
data:
  DATABASE_URL: "postgresql://finances:$(POSTGRES_PASSWORD)@postgres-shared.shared.svc.cluster.local:5432/finances"
  TRANSACTION_DATA_PATH: "/app/transaction_data"
  API_BASE_PATH: "/api"