name: Finance Platform CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'finances-website/**'
      - 'nginx/**'
      - 'k8s/finances-app/**'
      - 'k8s/database/**'
      - 'k8s/shared/**'
      - 'k8s/namespaces/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push-finances-app:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.modified, 'finances-website/') ||
      contains(github.event.head_commit.added, 'finances-website/') ||
      github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest
      
      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./finances-app/backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/finances-backend:latest,ghcr.io/${{ github.repository }}/finances-backend:${{ github.sha }}
          platforms: linux/arm64  # For Raspberry Pi 5
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./finances-app/frontend
          build-args: |
            NGINX_CONFIG_PATH=../../nginx
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/finances-frontend:latest,ghcr.io/${{ github.repository }}/finances-frontend:${{ github.sha }}
          platforms: linux/arm64  # For Raspberry Pi 5
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-kubernetes-config:
    needs: [build-and-push-finances-app]
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      - name: Update Kubernetes manifests with image SHA
        run: |
          # Update backend image
          sed -i "s|image: ghcr.io/${{ github.repository }}/finances-backend:.*|image: ghcr.io/${{ github.repository }}/finances-backend:${{ github.sha }}|g" k8s/finances-app/backend.yaml
          
          # Update frontend image
          sed -i "s|image: ghcr.io/${{ github.repository }}/finances-frontend:.*|image: ghcr.io/${{ github.repository }}/finances-frontend:${{ github.sha }}|g" k8s/finances-app/frontend.yaml
      
      - name: Apply Kubernetes configuration
        run: |
          # Apply in a specific order to ensure dependencies are met
          kubectl apply -f k8s/namespaces/
          kubectl apply -f k8s/shared/
          kubectl apply -f k8s/database/
          kubectl apply -f k8s/finances-app/
          kubectl apply -f k8s/ingress/
          
          # Verify deployments
          kubectl rollout status deployment -n finances-app finances-backend --timeout=180s
          kubectl rollout status deployment -n finances-app finances-frontend --timeout=180s
